version: "3"
services:
  backend:
    restart: always
    hostname: backend
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    build: backend/.
    volumes:
      - ./backend:/usr/src/app
  db:
    image: mariadb
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
